import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ScrollBar from "@/components/ScrollBar";
import Footer from "./components/Footer";
import GlobalLoader from "@/components/GlobalLoader";
import MotionCursor from "@/components/MotionCursor";
import ChatBox from "./components/ChatBox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JK-Portfolio",
  description: "Generated by create next app",
};

// ✅ Use LayoutProps type from Next.js
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GlobalLoader />
        <MotionCursor />
        <Header />
        {children}
        <ScrollBar />
        <Footer />
      </body>
    </html>
  );
}
